In [1]:
import pandas as pd

# Đọc file CSV bằng đường dẫn tương đối (bỏ qua một vài dòng bị lỗi định dạng dấu phẩy)
df = pd.read_csv('data/phone_dataset .csv', on_bad_lines='skip')

df.head()

  brand  ...                                            img_url
0  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-iconia...
1  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-liquid...
2  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-liquid...
3  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-iconia...
4  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-liquid...

[5 rows x 40 columns]

In [2]:
display(df.info())
display(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 8628 entries, 0 to 8627
Data columns (total 40 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brand               8628 non-null   str
 1   model               8628 non-null   str
 2   network_technology  8628 non-null   str
 3   2G_bands            8628 non-null   str
 4   3G_bands            4856 non-null   str
 5   4G_bands            1603 non-null   str
 6   network_speed       4883 non-null   str
 7   GPRS                8596 non-null   str
 8   EDGE                8605 non-null   str
 9   announced           8613 non-null   str
 10  status              8628 non-null   str
 11  dimentions          8609 non-null   str
 12  weight_g            7679 non-null   str
 13  weight_oz           7679 non-null   str
 14  SIM                 8627 non-null   str
 15  display_type        8624 non-null   str
 16  display_resolution  7414 non-null   str
 17  display_size        8581 non-null   str
 18  OS                  4905 non-null   str
 19  CPU                 4834 non-null   str
 20  Chipset             3690 non-null   str
 21  GPU                 3492 non-null   str
 22  memory_card         8628 non-null   str
 23  internal_memory     6806 non-null   str
 24  RAM                 4656 non-null   str
 25  primary_camera      7436 non-null   str
 26  secondary_camera    7405 non-null   str
 27  loud_speaker        8628 non-null   str
 28  audio_jack          8560 non-null   str
 29  WLAN                8624 non-null   str
 30  bluetooth           8609 non-null   str
 31  GPS                 8599 non-null   str
 32  NFC                 792 non-null    str
 33  radio               8534 non-null   str
 34  USB                 7725 non-null   str
 35  sensors             4588 non-null   str
 36  battery             8626 non-null   str
 37  colors              8026 non-null   str
 38  approx_price_EUR    5003 non-null   float64
 39  img_url             8628 non-null   str
dtypes: float64(1), str(39)
memory usage: 2.6 MB

None

       approx_price_EUR
count       5003.000000
mean         202.236458
std          600.183478
min           10.000000
25%           80.000000
50%          130.000000
75%          220.000000
max        27000.000000

**Ta có thể thấy phần lớn danh mục hiện tại đang ở dạng object, các thông tin ở dạng text khá nhiều và sẽ cần một quá trình xử lý để thu được các features cần thiết**

In [3]:
# Xác định các cột thuộc tính kỹ thuật chi tiết cần kiểm tra NaN
feature_cols = [
    'OS', 'CPU', 'Chipset', 'internal_memory', 'RAM',
    'display_type', 'display_resolution', 'display_size',
    'primary_camera', 'secondary_camera', 'battery'
]

# Loại bỏ các dòng không có giá bán (biến mục tiêu) và các thiết bị bị thiếu 3 trong các thông số kỹ thuật quan trọng (tránh làm thất thoát quá nhiều data)
df_cleaned = df.dropna(subset=['approx_price_EUR']).dropna(subset=feature_cols, thresh=7).copy()

print(f"Số lượng hàng trước khi xóa: {len(df)}")
print(f"Số lượng hàng sau khi xóa các hàng thiếu giá bán hoặc thiếu toàn bộ thông số: {len(df_cleaned)}")

# Gán lại vào df dưới dạng bản sao độc lập
df = df_cleaned
display(df.head())

Số lượng hàng trước khi xóa: 8628
Số lượng hàng sau khi xóa các hàng thiếu giá bán hoặc thiếu toàn bộ thông số: 4500

  brand  ...                                            img_url
0  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-iconia...
1  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-liquid...
2  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-liquid...
3  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-iconia...
4  Acer  ...  http://cdn2.gsmarena.com/vv/bigpic/acer-liquid...

[5 rows x 40 columns]

### Lọc bỏ các mẫu điện thoại cơ bản (máy cục gạch) và thiết bị không phải smartphone
Chúng ta sẽ nhận diện và loại bỏ các mẫu máy cục gạch dựa trên đặc điểm dung lượng bộ nhớ RAM hoặc ROM hiển thị dưới đơn vị `MB` thay vì `GB` (hoặc không có cả Hệ điều hành, CPU và RAM), đồng thời lọc bỏ các mẫu máy tính bảng (tablet), đồng hồ thông minh (smartwatch) và các dòng bị lỗi đơn vị tiền tệ để tránh ảnh hưởng đến các phân tích sau này.

In [4]:
import re
import pandas as pd

def is_non_target_smartphone(row):
    ram_str = str(row['RAM']).upper() if pd.notna(row['RAM']) else ''
    rom_str = str(row['internal_memory']).upper() if pd.notna(row['internal_memory']) else ''

    # 1. Lọc Feature Phone (Máy cục gạch)
    if 'MB' in ram_str or 'MB' in rom_str or '512 ROM' in rom_str:
        return True
    if pd.isna(row['OS']) and pd.isna(row['CPU']) and pd.isna(row['RAM']):
        return True

    # 2. Lọc Smartwatch, Tablet, Không hỗ trợ SIM
    os_str = str(row['OS']).upper() if pd.notna(row['OS']) else ''
    model_str = str(row['model']).upper()

    if 'WATCH' in os_str or 'WATCH' in model_str:
        return True
    if str(row['network_technology']).strip().upper() == 'NO CELLULAR CONNECTIVITY':
        return True
    if any(k in model_str for k in ['IPAD', 'TAB ', 'TAB-', 'TABLET', 'TOUGHPAD', 'FUNBOOK', 'STREAK', 'SPRINGBOARD']):
        return True

    # 3. Kích thước màn hình: Quét cả 2 cột vì dữ liệu bị nhầm lẫn
    res_str = str(row['display_resolution']) if pd.notna(row['display_resolution']) else ''
    size_str = str(row['display_size']) if pd.notna(row['display_size']) else ''
    combined_display_info = f"{res_str} {size_str}"

    m = re.search(r'(\d+(?:\.\d+)?)\s*inches', combined_display_info, re.IGNORECASE)
    if m:
        size_inch = float(m.group(1))
        # Vẫn nới ngưỡng lên 8.0 để giữ lại smartphone gập (VD: Z Fold 7.6 inch)
        if size_inch > 8.0 or size_inch < 3.0:
            return True

    # 4. Lọc Outlier giá và điện thoại thủ công
    if row['approx_price_EUR'] > 2500 or str(row['brand']).strip().upper() == 'VERTU':
        return True

    return False

# Áp dụng bộ lọc
initial_count = len(df)
df = df[~df.apply(is_non_target_smartphone, axis=1)].copy()

print(f"Số lượng thiết bị ban đầu: {initial_count}")
print(f"Số lượng máy sau khi lọc: {len(df)}")

Số lượng thiết bị ban đầu: 4500
Số lượng máy sau khi lọc: 1910

**Phần tiếp theo sẽ tách lấy các thông số quan trọng của 1 chiếc điện thoại**

### 1. Xử lý cột `RAM` và `internal_memory` để tách lấy RAM và ROM

In [5]:
import re
import pandas as pd
import numpy as np

def extract_ram_rom(row):
    ram_val = row['RAM']
    rom_val = row['internal_memory']

    # Tách lấy dung lượng RAM (ví dụ: "2 GB RAM", "3/4 GB RAM")
    ram = None
    if pd.notna(ram_val):
        s_ram = str(ram_val).upper()
        m_ram = re.findall(r'(?<![A-Z0-9])(\d+(?:\.\d+)?)\s*GB\s*RAM', s_ram)
        if not m_ram:
            m_ram = re.findall(r'(?<![A-Z0-9])(\d+(?:\.\d+)?)\s*GB', s_ram)
        vals = [float(x) for x in m_ram if float(x) <= 16]
        if vals:
            ram = f"{vals[0]} GB"

    # Tách lấy dung lượng bộ nhớ trong ROM (ví dụ: "16 GB", "16/32 GB")
    rom = None
    if pd.notna(rom_val):
        s_rom = str(rom_val).upper().strip()
        m_rom = re.findall(r'(?<![A-Z0-9])(\d+(?:\.\d+)?)\s*GB', s_rom)
        if m_rom:
            rom = f"{float(m_rom[0])} GB"
        elif re.match(r'^\d+(?:\.\d+)?$', s_rom):
            rom = f"{float(s_rom)} GB"

    return ram, rom

# Áp dụng hàm để chuẩn hóa cột RAM và tạo cột ROM
ram_rom_extracted = df.apply(extract_ram_rom, axis=1)
df['RAM_Clean'] = [x[0] for x in ram_rom_extracted]
df['ROM'] = [x[1] for x in ram_rom_extracted]

display(df[['RAM', 'internal_memory', 'RAM_Clean', 'ROM']].head())

        RAM internal_memory RAM_Clean      ROM
0  2 GB RAM        16/32 GB    2.0 GB  32.0 GB
1  3 GB RAM           32 GB    3.0 GB  32.0 GB
2  1 GB RAM            8 GB    1.0 GB   8.0 GB
4  3 GB RAM           32 GB    3.0 GB  32.0 GB
6  2 GB RAM           16 GB    2.0 GB  16.0 GB

### 2. Xử lý cụm cột Màn hình (`display_resolution`, `display_type`, `display_size`) để tách Kích thước, Tỷ lệ màn hình, Tấm nền và Độ phân giải
*(Lưu ý: Trong bộ dữ liệu gốc, hai cột `display_resolution` và `display_size` bị đặt ngược tên nhau — cột `display_resolution` chứa kích thước inch kèm tỷ lệ màn hình, còn `display_size` lại chứa độ phân giải pixels).*

In [6]:
def extract_screen_info(row):
    res_col = str(row['display_resolution']) if pd.notna(row['display_resolution']) else ""
    size_col = str(row['display_size']) if pd.notna(row['display_size']) else ""
    type_col = str(row['display_type']) if pd.notna(row['display_type']) else ""

    # 1. Kích thước màn hình: đi kèm chữ "inches"
    size_match = re.search(r'(\d+(?:\.\d+)?)\s*inches', res_col, re.IGNORECASE)
    size = f"{size_match.group(1)} inch" if size_match else None

    # 2. Tỷ lệ màn hình so với thân máy (screen-to-body ratio): đi kèm ký hiệu "%"
    ratio_match = re.search(r'(\d+(?:\.\d+)?)\s*%', res_col)
    screen_ratio = f"{ratio_match.group(1)} %" if ratio_match else None

    # 3. Tấm nền (Công nghệ màn hình): Super AMOLED, AMOLED, IPS LCD, Super LCD, TFT LCD...
    t_up = type_col.upper()
    if 'SUPER AMOLED' in t_up:
        panel = 'Super AMOLED'
    elif 'AMOLED' in t_up:
        panel = 'AMOLED'
    elif 'OLED' in t_up:
        panel = 'OLED'
    elif 'IPS' in t_up:
        panel = 'IPS LCD'
    elif 'SUPER LCD' in t_up or 'S-LCD' in t_up:
        panel = 'Super LCD'
    elif 'TFT' in t_up:
        panel = 'TFT LCD'
    elif 'PLS' in t_up:
        panel = 'PLS LCD'
    else:
        panel = None

    # 4. Độ phân giải: ví dụ 720 x 1280 pixels
    res_match = re.search(r'(\d+\s*[xX]\s*\d+\s*(?:Pixels|pixels)?)', size_col)
    resolution = res_match.group(1).strip() if res_match else None

    return size, screen_ratio, panel, resolution

# Áp dụng hàm tách thông tin màn hình
screen_extracted = df.apply(extract_screen_info, axis=1)
df['Kích Thước Màn Hình'] = [x[0] for x in screen_extracted]
df['Tỷ Lệ Màn Hình'] = [x[1] for x in screen_extracted]
df['Tấm Nền Màn Hình'] = [x[2] for x in screen_extracted]
df['Độ Phân Giải Màn Hình'] = [x[3] for x in screen_extracted]

display(df[['display_resolution', 'display_type', 'Kích Thước Màn Hình', 'Tỷ Lệ Màn Hình', 'Tấm Nền Màn Hình', 'Độ Phân Giải Màn Hình']].head(10))

                          display_resolution  ... Độ Phân Giải Màn Hình
0   7.0 inches (~69.8% screen-to-body ratio)  ...     720 x 1280 pixels
1   5.5 inches (~71.7% screen-to-body ratio)  ...    1080 x 1920 pixels
2                                 5.0 inches  ...     720 x 1280 pixels
4   5.5 inches (~69.0% screen-to-body ratio)  ...     720 x 1280 pixels
6   5.5 inches (~70.3% screen-to-body ratio)  ...     720 x 1280 pixels
7   5.0 inches (~66.4% screen-to-body ratio)  ...     720 x 1280 pixels
9   5.5 inches (~70.2% screen-to-body ratio)  ...    1080 x 1920 pixels
10  4.5 inches (~61.7% screen-to-body ratio)  ...      480 x 854 pixels
11  4.5 inches (~61.7% screen-to-body ratio)  ...      480 x 854 pixels
13  5.5 inches (~68.8% screen-to-body ratio)  ...     720 x 1280 pixels

[10 rows x 6 columns]

### 3. Xử lý cột `primary_camera` và `secondary_camera` để lấy độ phân giải Camera sau và Camera trước (MP)

In [7]:
def extract_camera_info(row):
    p_str = str(row['primary_camera']).upper() if pd.notna(row['primary_camera']) else ""
    s_str = str(row['secondary_camera']).upper() if pd.notna(row['secondary_camera']) else ""

    # Tách độ phân giải Camera sau lớn nhất
    mp_rear = re.findall(r'(?<![A-Z\d])(\d+(?:\.\d+)?)\s*MP', p_str)
    vals_p = [float(val) for val in mp_rear if float(val) <= 100]
    if vals_p:
        rear_cam = f"{max(vals_p)} MP"
    elif 'VGA' in p_str:
        rear_cam = "0.3 MP"
    else:
        rear_cam = None

    # Tách độ phân giải Camera trước (nếu ghi 'No' thì gán 0 MP, 'VGA' gán 0.3 MP)
    if s_str.strip() == 'NO':
        front_cam = "0 MP"
    else:
        mp_front = re.findall(r'(?<![A-Z\d])(\d+(?:\.\d+)?)\s*MP', s_str)
        vals_s = [float(val) for val in mp_front if float(val) <= 100]
        if vals_s:
            front_cam = f"{max(vals_s)} MP"
        elif 'VGA' in s_str:
            front_cam = "0.3 MP"
        else:
            front_cam = None

    return rear_cam, front_cam

# Áp dụng hàm để lấy độ phân giải camera sau và camera trước
camera_extracted = df.apply(extract_camera_info, axis=1)
df['Camera Sau'] = [x[0] for x in camera_extracted]
df['Camera Trước'] = [x[1] for x in camera_extracted]

display(df[['primary_camera', 'secondary_camera', 'Camera Sau', 'Camera Trước']].head(10))

                                       primary_camera  ... Camera Trước
0                                    13 MP| autofocus  ...       2.0 MP
1                         13 MP| autofocus| LED flash  ...       5.0 MP
2                          8 MP| autofocus| LED flash  ...       2.0 MP
4                13 MP| f/1.8| autofocus| LED flash|   ...      13.0 MP
6   13 MP| phase detection/laser autofocus| LED flash  ...       5.0 MP
7                   8 MP| f/2.0| autofocus| LED flash  ...       5.0 MP
9           21 MP| f/2.2| autofocus| dual-LED flash|   ...       8.0 MP
10                         5 MP| autofocus| LED flash  ...       5.0 MP
11                         5 MP| autofocus| LED flash  ...       2.0 MP
13                         8 MP| autofocus| LED flash  ...       8.0 MP

[10 rows x 4 columns]

### 4. Xử lý cột `battery` để lấy dung lượng Pin (mAh) và Thiết kế Pin (Nguyên khối / Tháo rời)

In [8]:
def extract_battery_info(text):
    if pd.isna(text):
        return None, None
    text_str = str(text)

    # Tìm dung lượng pin (ví dụ: 3400 mAh)
    battery_match = re.search(r'(\d+)\s*mAh', text_str, re.IGNORECASE)
    battery_capacity = f"{battery_match.group(1)} mAh" if battery_match else None

    # Xác định thiết kế pin liền máy (Non-removable) hay tháo rời (Removable)
    if 'NON-REMOVABLE' in text_str.upper():
        battery_design = 'Nguyên khối'
    else:
        battery_design = 'Tháo rời'

    return battery_capacity, battery_design

# Áp dụng hàm để lấy dung lượng pin và kiểu thiết kế pin
battery_extracted = df['battery'].apply(extract_battery_info)
df['Dung Lượng Pin'] = [x[0] for x in battery_extracted]
df['Thiết Kế Pin'] = [x[1] for x in battery_extracted]

display(df[['battery', 'Dung Lượng Pin', 'Thiết Kế Pin']].head(10))

                                             battery  ... Thiết Kế Pin
0   Non-removable Li-Ion 3400 mAh battery (12.92 Wh)  ...  Nguyên khối
1                   Removable Li-Po 4080 mAh battery  ...     Tháo rời
2                  Removable Li-Ion 2000 mAh battery  ...     Tháo rời
4                   Removable Li-Po 4020 mAh battery  ...     Tháo rời
6              Non-removable Li-Ion 5000 mAh battery  ...  Nguyên khối
7                  Removable Li-Ion 2000 mAh battery  ...     Tháo rời
9               Non-removable Li-Po 2870 mAh battery  ...  Nguyên khối
10                 Removable Li-Ion 2000 mAh battery  ...     Tháo rời
11                  Removable Li-Po 2000 mAh battery  ...     Tháo rời
13                 Removable Li-Ion 4000 mAh battery  ...     Tháo rời

[10 rows x 3 columns]

### 5. Xử lý thông số kích thước (`dimentions`), trọng lượng (`weight_g`) và kiểm tra tính năng Cảm biến vân tay (`sensors`)

In [9]:
def extract_design_and_sensors(row):
    dim_text = str(row['dimentions']) if pd.notna(row['dimentions']) else ""
    sensors_text = str(row['sensors']) if pd.notna(row['sensors']) else ""

    # 1. Tách độ dày thân máy (mm) từ chuỗi kích thước Dài x Rộng x Dày mm
    thick_match = re.search(r'x\s*\d+(?:\.\d+)?\s*x\s*(\d+(?:\.\d+)?)\s*mm', dim_text, re.IGNORECASE)
    if not thick_match:
        thick_match = re.search(r'(\d+(?:\.\d+)?)\s*mm\s*thickness', dim_text, re.IGNORECASE)
    thickness = f"{thick_match.group(1)} mm" if thick_match else None

    # 2. Chuẩn hóa trọng lượng máy (g)
    w_val = pd.to_numeric(row['weight_g'], errors='coerce')
    weight = f"{w_val} g" if pd.notna(w_val) else None

    # 3. Kiểm tra trang bị cảm biến vân tay (Fingerprint)
    if re.search(r'fingerprint', sensors_text, re.IGNORECASE):
        fingerprint = "Có"
    else:
        fingerprint = "Không"

    return thickness, weight, fingerprint

# Áp dụng hàm để lấy độ dày, trọng lượng và cảm biến vân tay
design_extracted = df.apply(extract_design_and_sensors, axis=1)
df['Độ Dày'] = [x[0] for x in design_extracted]
df['Trọng Lượng'] = [x[1] for x in design_extracted]
df['Cảm Biến Vân Tay'] = [x[2] for x in design_extracted]

display(df[['dimentions', 'weight_g', 'sensors', 'Độ Dày', 'Trọng Lượng', 'Cảm Biến Vân Tay']].head(10))

                                       dimentions  ... Cảm Biến Vân Tay
0    191.7 x 101 x 9.4 mm (7.55 x 3.98 x 0.37 in)  ...            Không
1   153.8 x 75.6 x 8.5 mm (6.06 x 2.98 x 0.33 in)  ...               Có
2                                               -  ...            Không
4   153.3 x 78.8 x 8.5 mm (6.04 x 3.10 x 0.33 in)  ...            Không
6        154 x 77 x 10 mm (6.06 x 3.03 x 0.39 in)  ...            Không
7   145.7 x 71.2 x 8.4 mm (5.74 x 2.80 x 0.33 in)  ...            Không
9   156.5 x 75.9 x 8.4 mm (6.16 x 2.99 x 0.33 in)  ...            Không
10    136 x 66.5 x 9.6 mm (5.35 x 2.62 x 0.38 in)  ...            Không
11    136 x 66.5 x 9.6 mm (5.35 x 2.62 x 0.38 in)  ...            Không
13  156.3 x 77.5 x 8.9 mm (6.15 x 3.05 x 0.35 in)  ...            Không

[10 rows x 6 columns]

### 6. Kiểm tra hỗ trợ kết nối mạng di động (2G, 3G hoặc 4G LTE)

In [10]:
def check_network_support(row):
    net_tech = str(row['network_technology']) if pd.notna(row['network_technology']) else ""
    bands_4g = str(row['4G_bands']) if pd.notna(row['4G_bands']) else ""
    combined_text = (net_tech + " " + bands_4g).upper()

    # Kiểm tra sự xuất hiện của chuẩn mạng cao nhất mà máy hỗ trợ
    if "LTE" in combined_text or "4G" in combined_text:
        return "4G / LTE"
    elif any(k in combined_text for k in ["HSPA", "3G", "UMTS", "EVDO"]):
        return "3G"
    else:
        return "2G"

# Áp dụng hàm để xác định loại mạng hỗ trợ
df['Hỗ Trợ Mạng'] = df.apply(check_network_support, axis=1)

display(df[['network_technology', '4G_bands', 'Hỗ Trợ Mạng']].head(10))

   network_technology  ... Hỗ Trợ Mạng
0    GSM / HSPA / LTE  ...    4G / LTE
1    GSM / HSPA / LTE  ...    4G / LTE
2    GSM / HSPA / LTE  ...    4G / LTE
4    GSM / HSPA / LTE  ...    4G / LTE
6    GSM / HSPA / LTE  ...    4G / LTE
7    GSM / HSPA / LTE  ...    4G / LTE
9    GSM / HSPA / LTE  ...    4G / LTE
10   GSM / HSPA / LTE  ...    4G / LTE
11         GSM / HSPA  ...          3G
13   GSM / HSPA / LTE  ...    4G / LTE

[10 rows x 3 columns]

### 7. Trích xuất Hãng Thiết kế Chip, Số Nhân CPU và Xung Nhịp CPU

In [11]:
def extract_chip_info(row):
    cpu_str = str(row['CPU']).strip() if pd.notna(row['CPU']) else ""
    chip_str = str(row['Chipset']).strip() if pd.notna(row['Chipset']) else ""
    combined_upper = (chip_str + " " + cpu_str).upper()

    # 1. Trích xuất hãng chip (Brand)
    if "SNAPDRAGON" in combined_upper or "QUALCOMM" in combined_upper:
        brand = "Snapdragon"
    elif any(k in combined_upper for k in ["MEDIATEK", "HELIO", "MT6", "MT8"]):
        brand = "MediaTek"
    elif "EXYNOS" in combined_upper:
        brand = "Exynos"
    elif "APPLE" in combined_upper or str(row['brand']).strip().upper() == "APPLE":
        brand = "Apple"
    elif "KIRIN" in combined_upper or "HISILICON" in combined_upper:
        brand = "Kirin"
    elif "SPREADTRUM" in combined_upper:
        brand = "Spreadtrum"
    elif "INTEL" in combined_upper or "ATOM" in combined_upper:
        brand = "Intel"
    elif pd.isna(row['Chipset']):
        brand = None
    else:
        brand = "Khác"

    # 2. Trích xuất số nhân CPU (Cores)
    cpu_upper = cpu_str.upper()
    if not cpu_str:
        cores = None
    elif "DECA-CORE" in cpu_upper or "10-CORE" in cpu_upper:
        cores = "10 nhân"
    elif "OCTA-CORE" in cpu_upper or "8-CORE" in cpu_upper:
        cores = "8 nhân"
    elif "HEXA-CORE" in cpu_upper or "6-CORE" in cpu_upper:
        cores = "6 nhân"
    elif "QUAD-CORE" in cpu_upper or "4-CORE" in cpu_upper:
        cores = "4 nhân"
    elif "DUAL-CORE" in cpu_upper or "2-CORE" in cpu_upper:
        cores = "2 nhân"
    else:
        cores = "1 nhân"

    # 3. Trích xuất xung nhịp tối đa (GHz)
    ghz_matches = re.findall(r'(\d+(?:\.\d+)?)\s*GHz', cpu_str, re.IGNORECASE)
    if ghz_matches:
        clock = f"{max([float(x) for x in ghz_matches])} GHz"
    else:
        mhz_matches = re.findall(r'(\d+(?:\.\d+)?)\s*MHz', cpu_str, re.IGNORECASE)
        clock = f"{round(max([float(x) for x in mhz_matches]) / 1000.0, 2)} GHz" if mhz_matches else None

    return brand, cores, clock

# Áp dụng hàm để tạo 3 cột thông số vi xử lý
chip_extracted = df.apply(extract_chip_info, axis=1)
df['Hãng Chip'] = [x[0] for x in chip_extracted]
df['Số Nhân CPU'] = [x[1] for x in chip_extracted]
df['Xung Nhịp CPU'] = [x[2] for x in chip_extracted]

display(df[['Chipset', 'CPU', 'Hãng Chip', 'Số Nhân CPU', 'Xung Nhịp CPU']].head(10))

                            Chipset  ... Xung Nhịp CPU
0                   Mediatek MT8735  ...       1.3 GHz
1                   Mediatek MT6753  ...       1.3 GHz
2                   Mediatek MT6737  ...      1.25 GHz
4                   Mediatek MT6753  ...       1.3 GHz
6                   Mediatek MT6735  ...       1.3 GHz
7            Mediatek MT6580 - Z525  ...       1.3 GHz
9   Qualcomm MSM8992 Snapdragon 808  ...       1.8 GHz
10  Qualcomm MSM8909 Snapdragon 210  ...       1.1 GHz
11  Qualcomm MSM8909 Snapdragon 210  ...       1.0 GHz
13                  Mediatek MT6735  ...       1.3 GHz

[10 rows x 5 columns]

**Ở phần kết nối, em chỉ lựa chọn xem máy hỗ trợ mạng 2G, 3G hay 4G LTE vì các chuẩn khác như Wifi hay Bluetooth thường không được người dùng quan tâm nhiều**

**Còn lại các trường thông tin không cần thiết như tên máy, hệ điều hành chi tiết, trạng thái, đường dẫn ảnh,... thì em sẽ loại bỏ**

### Trích xuất thêm Năm Ra Mắt, chuẩn hóa NFC và loại bỏ các cột văn bản thô không cần thiết
Chúng ta trích xuất năm ra mắt (4 chữ số) từ cột `announced`, mã hóa nhị phân cột `NFC` (`1`: có hỗ trợ, `0`: không hỗ trợ), chuẩn hóa tên cột hãng sản xuất, giá bán và loại bỏ các cột văn bản thô ban đầu không còn cần thiết cho việc phân tích, đồng thời reset lại chỉ mục (index).

In [12]:
import pandas as pd

# Đưa chỉ mục về dạng mặc định từ 0
df_final = df.reset_index(drop=True)

# 1. Xử lý cột announced (Chỉ trích xuất năm - 4 chữ số)
# Nếu không tìm thấy năm, nó sẽ tự thành NaN
df_final['Năm Ra Mắt'] = df_final['announced'].astype(str).str.extract(r'(\d{4})').astype(float)

# 2. Xử lý cột NFC (Có data -> 1, NaN -> 0)
df_final['NFC_Clean'] = df_final['NFC'].notna().astype(int)

# Chuẩn hóa cột Hãng Sản Xuất, Giá Bán (EUR) và gán lại cột RAM đã tách
df_final['Hãng Sản Xuất'] = df_final['brand'].astype(str).str.strip()
df_final['Giá Bán (EUR)'] = df_final['approx_price_EUR']
df_final['RAM'] = df_final['RAM_Clean']

# Xác định danh sách các cột văn bản thô không cần thiết để xóa
# Đã thêm 'announced' và 'NFC' gốc vào danh sách xóa vì ta đã tạo cột Clean ở trên
cols_to_drop = [
    'brand', 'model', 'network_technology', '2G_bands', '3G_bands', '4G_bands',
    'network_speed', 'GPRS', 'EDGE', 'status', 'dimentions',
    'weight_g', 'weight_oz', 'SIM', 'display_type', 'display_resolution',
    'display_size', 'OS', 'CPU', 'Chipset', 'GPU', 'memory_card',
    'internal_memory', 'RAM_Clean', 'primary_camera', 'secondary_camera',
    'loud_speaker', 'audio_jack', 'WLAN', 'bluetooth', 'GPS',
    'radio', 'USB', 'sensors', 'battery', 'colors', 'approx_price_EUR', 'img_url',
    'announced', 'NFC'
]

df_final = df_final.drop(columns=cols_to_drop, errors='ignore')

print(f"Kích thước bộ dữ liệu sau khi lọc cột: {df_final.shape}")
pd.set_option('display.max_columns', None)
display(df_final.head(10))

Kích thước bộ dữ liệu sau khi lọc cột: (1910, 21)

,RAM,ROM,Kích Thước Màn Hình,Tỷ Lệ Màn Hình,Tấm Nền Màn Hình,Độ Phân Giải Màn Hình,Camera Sau,Camera Trước,Dung Lượng Pin,Thiết Kế Pin,Độ Dày,Trọng Lượng,Cảm Biến Vân Tay,Hỗ Trợ Mạng,Hãng Chip,Số Nhân CPU,Xung Nhịp CPU,Năm Ra Mắt,NFC_Clean,Hãng Sản Xuất,Giá Bán (EUR)
0,2.0 GB,32.0 GB,7.0 inch,69.8 %,IPS LCD,720 x 1280 pixels,13.0 MP,2.0 MP,3400 mAh,Nguyên khối,9.4 mm,260 g,Không,4G / LTE,MediaTek,4 nhân,1.3 GHz,2016.0,0,Acer,170.0
1,3.0 GB,32.0 GB,5.5 inch,71.7 %,IPS LCD,1080 x 1920 pixels,13.0 MP,5.0 MP,4080 mAh,Tháo rời,8.5 mm,169 g,Có,4G / LTE,MediaTek,8 nhân,1.3 GHz,2016.0,0,Acer,250.0
2,1.0 GB,8.0 GB,5.0 inch,NaN,IPS LCD,720 x 1280 pixels,8.0 MP,2.0 MP,2000 mAh,Tháo rời,NaN,NaN,Không,4G / LTE,MediaTek,4 nhân,1.25 GHz,2016.0,0,Acer,120.0
3,3.0 GB,32.0 GB,5.5 inch,69.0 %,IPS LCD,720 x 1280 pixels,13.0 MP,13.0 MP,4020 mAh,Tháo rời,8.5 mm,166 g,Không,4G / LTE,MediaTek,8 nhân,1.3 GHz,2015.0,0,Acer,230.0
4,2.0 GB,16.0 GB,5.5 inch,70.3 %,IPS LCD,720 x 1280 pixels,13.0 MP,5.0 MP,5000 mAh,Nguyên khối,10 mm,NaN,Không,4G / LTE,MediaTek,4 nhân,1.3 GHz,2016.0,0,Acer,200.0
5,1.0 GB,8.0 GB,5.0 inch,66.4 %,IPS LCD,720 x 1280 pixels,8.0 MP,5.0 MP,2000 mAh,Tháo rời,8.4 mm,125 g,Không,4G / LTE,MediaTek,4 nhân,1.3 GHz,2016.0,0,Acer,110.0
6,3.0 GB,32.0 GB,5.5 inch,70.2 %,AMOLED,1080 x 1920 pixels,21.0 MP,8.0 MP,2870 mAh,Nguyên khối,8.4 mm,150 g,Không,4G / LTE,Snapdragon,6 nhân,1.8 GHz,2015.0,0,Acer,220.0
7,1.0 GB,8.0 GB,4.5 inch,61.7 %,IPS LCD,480 x 854 pixels,5.0 MP,5.0 MP,2000 mAh,Tháo rời,9.6 mm,142 g,Không,4G / LTE,Snapdragon,4 nhân,1.1 GHz,2015.0,0,Acer,110.0
8,1.0 GB,8.0 GB,4.5 inch,61.7 %,IPS LCD,480 x 854 pixels,5.0 MP,2.0 MP,2000 mAh,Tháo rời,9.6 mm,142 g,Không,3G,Snapdragon,4 nhân,1.0 GHz,2015.0,0,Acer,90.0
9,1.0 GB,8.0 GB,5.5 inch,68.8 %,IPS LCD,720 x 1280 pixels,8.0 MP,8.0 MP,4000 mAh,Tháo rời,8.9 mm,165 g,Không,4G / LTE,MediaTek,4 nhân,1.3 GHz,2015.0,0,Acer,200.0

**Tiếp đến, em sẽ gom tất cả các features đã được tách ra để tạo thành 1 bảng mới**

In [13]:
# Sắp xếp và gom các cột thông tin đã được chuẩn hóa và trích xuất
selected_features = [
    'Hãng Sản Xuất', 'Giá Bán (EUR)',
    'RAM', 'ROM',
    'Kích Thước Màn Hình', 'Tỷ Lệ Màn Hình', 'Tấm Nền Màn Hình', 'Độ Phân Giải Màn Hình',
    'Camera Sau', 'Camera Trước',
    'Dung Lượng Pin', 'Thiết Kế Pin',
    'Độ Dày', 'Trọng Lượng',
    'Cảm Biến Vân Tay', 'Hỗ Trợ Mạng',
    'Hãng Chip', 'Số Nhân CPU', 'Xung Nhịp CPU',
    'Năm Ra Mắt', 'NFC_Clean'
]

# Tạo bảng mới chứa các thuộc tính đã xử lý
df_features = df_final[selected_features].copy()

print(f"Kích thước bảng thuộc tính mới: {df_features.shape}")
display(df_features.head(5))

Kích thước bảng thuộc tính mới: (1910, 21)

,Hãng Sản Xuất,Giá Bán (EUR),RAM,ROM,Kích Thước Màn Hình,Tỷ Lệ Màn Hình,Tấm Nền Màn Hình,Độ Phân Giải Màn Hình,Camera Sau,Camera Trước,Dung Lượng Pin,Thiết Kế Pin,Độ Dày,Trọng Lượng,Cảm Biến Vân Tay,Hỗ Trợ Mạng,Hãng Chip,Số Nhân CPU,Xung Nhịp CPU,Năm Ra Mắt,NFC_Clean
0,Acer,170.0,2.0 GB,32.0 GB,7.0 inch,69.8 %,IPS LCD,720 x 1280 pixels,13.0 MP,2.0 MP,3400 mAh,Nguyên khối,9.4 mm,260 g,Không,4G / LTE,MediaTek,4 nhân,1.3 GHz,2016.0,0
1,Acer,250.0,3.0 GB,32.0 GB,5.5 inch,71.7 %,IPS LCD,1080 x 1920 pixels,13.0 MP,5.0 MP,4080 mAh,Tháo rời,8.5 mm,169 g,Có,4G / LTE,MediaTek,8 nhân,1.3 GHz,2016.0,0
2,Acer,120.0,1.0 GB,8.0 GB,5.0 inch,NaN,IPS LCD,720 x 1280 pixels,8.0 MP,2.0 MP,2000 mAh,Tháo rời,NaN,NaN,Không,4G / LTE,MediaTek,4 nhân,1.25 GHz,2016.0,0
3,Acer,230.0,3.0 GB,32.0 GB,5.5 inch,69.0 %,IPS LCD,720 x 1280 pixels,13.0 MP,13.0 MP,4020 mAh,Tháo rời,8.5 mm,166 g,Không,4G / LTE,MediaTek,8 nhân,1.3 GHz,2015.0,0
4,Acer,200.0,2.0 GB,16.0 GB,5.5 inch,70.3 %,IPS LCD,720 x 1280 pixels,13.0 MP,5.0 MP,5000 mAh,Nguyên khối,10 mm,NaN,Không,4G / LTE,MediaTek,4 nhân,1.3 GHz,2016.0,0

**Ở các cột có đơn vị, em sẽ tiến hành loại bỏ đơn vị đi**

In [14]:
import pandas as pd
import numpy as np

# Tạo một bản sao để tránh cảnh báo SettingWithCopyWarning
df_features = df_features.copy()

# Thay vì tìm chính xác chuỗi ' GB', ta dùng Regex để xóa mọi ký tự đơn vị và khoảng trắng
# Chỉ giữ lại các chữ số (0-9) và dấu chấm (.) để chuyển đổi an toàn
unit_columns = [
    'RAM', 'ROM', 'Kích Thước Màn Hình', 'Tỷ Lệ Màn Hình', 
    'Camera Sau', 'Camera Trước', 'Dung Lượng Pin', 
    'Độ Dày', 'Trọng Lượng', 'Số Nhân CPU', 'Xung Nhịp CPU'
]

for col in unit_columns:
    if col in df_features.columns:
        # Xóa các ký tự đơn vị (kể cả '%' hay chữ tiếng Việt như 'nhân') và khoảng trắng bằng Regex
        df_features[col] = df_features[col].astype(str).str.replace(r'[^\d.]+', '', regex=True)
        # Chuyển về dạng số, các chuỗi 'nan' hoặc lỗi sẽ thành NaN
        df_features[col] = pd.to_numeric(df_features[col], errors='coerce')

# Đổi tên cột để người dùng vẫn biết đơn vị gốc sau khi bỏ chữ
rename_dict = {
    'RAM': 'RAM (GB)',
    'ROM': 'ROM (GB)',
    'Kích Thước Màn Hình': 'Kích Thước Màn Hình (inch)',
    'Tỷ Lệ Màn Hình': 'Tỷ Lệ Màn Hình (%)',
    'Camera Sau': 'Camera Sau (MP)',
    'Camera Trước': 'Camera Trước (MP)',
    'Dung Lượng Pin': 'Dung Lượng Pin (mAh)',
    'Độ Dày': 'Độ Dày (mm)',
    'Trọng Lượng': 'Trọng Lượng (g)',
    'Số Nhân CPU': 'Số Nhân CPU (Core)',
    'Xung Nhịp CPU': 'Xung Nhịp CPU (GHz)'
}
df_features = df_features.rename(columns=rename_dict)

# Hiển thị kết quả sau khi làm sạch đơn vị
display(df_features.head(15))

# Chỉ gọi info(), không cần bọc trong display()
df_features.info()

<class 'pandas.DataFrame'>
RangeIndex: 1910 entries, 0 to 1909
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hãng Sản Xuất               1910 non-null   str
 1   Giá Bán (EUR)               1910 non-null   float64
 2   RAM (GB)                    1792 non-null   float64
 3   ROM (GB)                    1838 non-null   float64
 4   Kích Thước Màn Hình (inch)  1905 non-null   float64
 5   Tỷ Lệ Màn Hình (%)          1832 non-null   float64
 6   Tấm Nền Màn Hình            1762 non-null   str
 7   Độ Phân Giải Màn Hình       1905 non-null   str
 8   Camera Sau (MP)             1908 non-null   float64
 9   Camera Trước (MP)           1861 non-null   float64
 10  Dung Lượng Pin (mAh)        1872 non-null   float64
 11  Thiết Kế Pin                1910 non-null   str
 12  Độ Dày (mm)                 1824 non-null   float64
 13  Trọng Lượng (g)             1690 non-null   float64
 14  Cảm Biến Vân Tay            1910 non-null   str
 15  Hỗ Trợ Mạng                 1910 non-null   str
 16  Hãng Chip                   1684 non-null   str
 17  Số Nhân CPU (Core)          1885 non-null   float64
 18  Xung Nhịp CPU (GHz)         1877 non-null   float64
 19  Năm Ra Mắt                  1909 non-null   float64
 20  NFC_Clean                   1910 non-null   int64
dtypes: float64(13), int64(1), str(7)
memory usage: 313.5 KB

,Hãng Sản Xuất,Giá Bán (EUR),RAM (GB),ROM (GB),Kích Thước Màn Hình (inch),Tỷ Lệ Màn Hình (%),Tấm Nền Màn Hình,Độ Phân Giải Màn Hình,Camera Sau (MP),Camera Trước (MP),Dung Lượng Pin (mAh),Thiết Kế Pin,Độ Dày (mm),Trọng Lượng (g),Cảm Biến Vân Tay,Hỗ Trợ Mạng,Hãng Chip,Số Nhân CPU (Core),Xung Nhịp CPU (GHz),Năm Ra Mắt,NFC_Clean
0,Acer,170.0,2.0,32.0,7.0,69.8,IPS LCD,720 x 1280 pixels,13.0,2.0,3400.0,Nguyên khối,9.4,260.0,Không,4G / LTE,MediaTek,4.0,1.30,2016.0,0
1,Acer,250.0,3.0,32.0,5.5,71.7,IPS LCD,1080 x 1920 pixels,13.0,5.0,4080.0,Tháo rời,8.5,169.0,Có,4G / LTE,MediaTek,8.0,1.30,2016.0,0
2,Acer,120.0,1.0,8.0,5.0,NaN,IPS LCD,720 x 1280 pixels,8.0,2.0,2000.0,Tháo rời,NaN,NaN,Không,4G / LTE,MediaTek,4.0,1.25,2016.0,0
3,Acer,230.0,3.0,32.0,5.5,69.0,IPS LCD,720 x 1280 pixels,13.0,13.0,4020.0,Tháo rời,8.5,166.0,Không,4G / LTE,MediaTek,8.0,1.30,2015.0,0
4,Acer,200.0,2.0,16.0,5.5,70.3,IPS LCD,720 x 1280 pixels,13.0,5.0,5000.0,Nguyên khối,10.0,NaN,Không,4G / LTE,MediaTek,4.0,1.30,2016.0,0
5,Acer,110.0,1.0,8.0,5.0,66.4,IPS LCD,720 x 1280 pixels,8.0,5.0,2000.0,Tháo rời,8.4,125.0,Không,4G / LTE,MediaTek,4.0,1.30,2016.0,0
6,Acer,220.0,3.0,32.0,5.5,70.2,AMOLED,1080 x 1920 pixels,21.0,8.0,2870.0,Nguyên khối,8.4,150.0,Không,4G / LTE,Snapdragon,6.0,1.80,2015.0,0
7,Acer,110.0,1.0,8.0,4.5,61.7,IPS LCD,480 x 854 pixels,5.0,5.0,2000.0,Tháo rời,9.6,142.0,Không,4G / LTE,Snapdragon,4.0,1.10,2015.0,0
8,Acer,90.0,1.0,8.0,4.5,61.7,IPS LCD,480 x 854 pixels,5.0,2.0,2000.0,Tháo rời,9.6,142.0,Không,3G,Snapdragon,4.0,1.00,2015.0,0
9,Acer,200.0,1.0,8.0,5.5,68.8,IPS LCD,720 x 1280 pixels,8.0,8.0,4000.0,Tháo rời,8.9,165.0,Không,4G / LTE,MediaTek,4.0,1.30,2015.0,0
10,Acer,150.0,1.0,8.0,5.0,68.1,IPS LCD,720 x 1280 pixels,8.0,8.0,2420.0,Tháo rời,8.9,145.0,Không,4G / LTE,MediaTek,4.0,1.30,2015.0,0
11,Acer,200.0,1.0,8.0,5.0,68.8,IPS LCD,720 x 1280 pixels,13.0,5.0,2300.0,Nguyên khối,8.0,110.0,Không,4G / LTE,MediaTek,4.0,1.50,2015.0,0
12,Acer,130.0,1.0,8.0,5.0,57.1,TFT LCD,480 x 854 pixels,8.0,2.0,2000.0,Tháo rời,6.4,118.0,Không,3G,MediaTek,4.0,1.30,2015.0,0
13,Acer,90.0,1.0,8.0,4.0,56.8,NaN,480 x 800 pixels,5.0,2.0,1300.0,Tháo rời,9.6,120.0,Không,3G,Snapdragon,2.0,1.20,2015.0,0
14,Acer,130.0,1.0,8.0,4.5,61.5,IPS LCD,540 x 960 pixels,5.0,2.0,2000.0,Tháo rời,9.9,145.0,Không,4G / LTE,MediaTek,4.0,1.30,2015.0,0

**Ở phần độ phân giải màn hình, em sẽ bỏ phần đơn vị đi, tính số pixel đường chéo, để sau này sẽ tiện tính PPI, tạo thành feature là số pixel**

In [15]:
import re
import pandas as pd
import numpy as np

def calculate_diagonal_pixels(resolution_str):
    if pd.isna(resolution_str):
        return np.nan
    # Tìm các chuỗi số có dạng: số1 x số2 hoặc số1 X số2
    match = re.search(r'(\d+)\s*[xX]\s*(\d+)', str(resolution_str))
    if match:
        width = int(match.group(1))
        height = int(match.group(2))
        # Tính Pytago: căn bậc hai của (width^2 + height^2)
        return np.sqrt(width**2 + height**2)
    return np.nan

# Áp dụng hàm để tính số pixel trên đường chéo và bỏ cột chuỗi độ phân giải gốc
if 'Độ Phân Giải Màn Hình' in df_features.columns:
    df_features['Độ Phân Giải Đường Chéo (Pixels)'] = df_features['Độ Phân Giải Màn Hình'].apply(calculate_diagonal_pixels)
    df_features = df_features.drop(columns=['Độ Phân Giải Màn Hình'])

display(df_features[['Hãng Sản Xuất', 'Độ Phân Giải Đường Chéo (Pixels)']].head(10))
print(df_features['Độ Phân Giải Đường Chéo (Pixels)'].dtype)

float64

  Hãng Sản Xuất  Độ Phân Giải Đường Chéo (Pixels)
0          Acer                       1468.604780
1          Acer                       2202.907170
2          Acer                       1468.604780
3          Acer                       1468.604780
4          Acer                       1468.604780
5          Acer                       1468.604780
6          Acer                       2202.907170
7          Acer                        979.650958
8          Acer                        979.650958
9          Acer                       1468.604780

In [16]:
# Hiển thị 10 dòng đầu tiên của bảng dữ liệu đã xử lý hoàn tất
display(df_features.head(10))

# Hiển thị thông tin tổng quan về các cột dữ liệu hiện tại
df_features.info()

<class 'pandas.DataFrame'>
RangeIndex: 1910 entries, 0 to 1909
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hãng Sản Xuất                     1910 non-null   str
 1   Giá Bán (EUR)                     1910 non-null   float64
 2   RAM (GB)                          1792 non-null   float64
 3   ROM (GB)                          1838 non-null   float64
 4   Kích Thước Màn Hình (inch)        1905 non-null   float64
 5   Tỷ Lệ Màn Hình (%)                1832 non-null   float64
 6   Tấm Nền Màn Hình                  1762 non-null   str
 7   Camera Sau (MP)                   1908 non-null   float64
 8   Camera Trước (MP)                 1861 non-null   float64
 9   Dung Lượng Pin (mAh)              1872 non-null   float64
 10  Thiết Kế Pin                      1910 non-null   str
 11  Độ Dày (mm)                       1824 non-null   float64
 12  Trọng Lượng (g)                   1690 non-null   float64
 13  Cảm Biến Vân Tay                  1910 non-null   str
 14  Hỗ Trợ Mạng                       1910 non-null   str
 15  Hãng Chip                         1684 non-null   str
 16  Số Nhân CPU (Core)                1885 non-null   float64
 17  Xung Nhịp CPU (GHz)               1877 non-null   float64
 18  Năm Ra Mắt                        1909 non-null   float64
 19  NFC_Clean                         1910 non-null   int64
 20  Độ Phân Giải Đường Chéo (Pixels)  1905 non-null   float64
dtypes: float64(14), int64(1), str(6)
memory usage: 313.5 KB

,Hãng Sản Xuất,Giá Bán (EUR),RAM (GB),ROM (GB),Kích Thước Màn Hình (inch),Tỷ Lệ Màn Hình (%),Tấm Nền Màn Hình,Camera Sau (MP),Camera Trước (MP),Dung Lượng Pin (mAh),Thiết Kế Pin,Độ Dày (mm),Trọng Lượng (g),Cảm Biến Vân Tay,Hỗ Trợ Mạng,Hãng Chip,Số Nhân CPU (Core),Xung Nhịp CPU (GHz),Năm Ra Mắt,NFC_Clean,Độ Phân Giải Đường Chéo (Pixels)
0,Acer,170.0,2.0,32.0,7.0,69.8,IPS LCD,13.0,2.0,3400.0,Nguyên khối,9.4,260.0,Không,4G / LTE,MediaTek,4.0,1.30,2016.0,0,1468.604780
1,Acer,250.0,3.0,32.0,5.5,71.7,IPS LCD,13.0,5.0,4080.0,Tháo rời,8.5,169.0,Có,4G / LTE,MediaTek,8.0,1.30,2016.0,0,2202.907170
2,Acer,120.0,1.0,8.0,5.0,NaN,IPS LCD,8.0,2.0,2000.0,Tháo rời,NaN,NaN,Không,4G / LTE,MediaTek,4.0,1.25,2016.0,0,1468.604780
3,Acer,230.0,3.0,32.0,5.5,69.0,IPS LCD,13.0,13.0,4020.0,Tháo rời,8.5,166.0,Không,4G / LTE,MediaTek,8.0,1.30,2015.0,0,1468.604780
4,Acer,200.0,2.0,16.0,5.5,70.3,IPS LCD,13.0,5.0,5000.0,Nguyên khối,10.0,NaN,Không,4G / LTE,MediaTek,4.0,1.30,2016.0,0,1468.604780
5,Acer,110.0,1.0,8.0,5.0,66.4,IPS LCD,8.0,5.0,2000.0,Tháo rời,8.4,125.0,Không,4G / LTE,MediaTek,4.0,1.30,2016.0,0,1468.604780
6,Acer,220.0,3.0,32.0,5.5,70.2,AMOLED,21.0,8.0,2870.0,Nguyên khối,8.4,150.0,Không,4G / LTE,Snapdragon,6.0,1.80,2015.0,0,2202.907170
7,Acer,110.0,1.0,8.0,4.5,61.7,IPS LCD,5.0,5.0,2000.0,Tháo rời,9.6,142.0,Không,4G / LTE,Snapdragon,4.0,1.10,2015.0,0,979.650958
8,Acer,90.0,1.0,8.0,4.5,61.7,IPS LCD,5.0,2.0,2000.0,Tháo rời,9.6,142.0,Không,3G,Snapdragon,4.0,1.00,2015.0,0,979.650958
9,Acer,200.0,1.0,8.0,5.5,68.8,IPS LCD,8.0,8.0,4000.0,Tháo rời,8.9,165.0,Không,4G / LTE,MediaTek,4.0,1.30,2015.0,0,1468.604780

In [17]:
# Xuất DataFrame đã làm sạch ra file CSV
cleaned_file_path = 'phone_dataset_cleaned.csv'
df_features.to_csv(cleaned_file_path, index=False, encoding='utf-8-sig')
print(f"Đã lưu thành công file '{cleaned_file_path}' với {len(df_features)} dòng dữ liệu.")

Đã lưu thành công file 'phone_dataset_cleaned.csv' với 1910 dòng dữ liệu.